---

# Alpine linux kernel parameters configuration

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

- name: Install apk packages - ip6tables ufw
  command: /sbin/apk add ip6tables ufw

- name: Allow incoming connections on tcp {{ ansible_port }}
  command: /usr/sbin/ufw allow {{ ansible_port }}/tcp

# see https://github.com/docker/hub-feedback/issues/2421
- name: Denying IPv6 access to DockerHub, it fail back to ipv4 which works.
  command: /usr/sbin/ufw deny out from any to 2600:1f18:2148:bc00::/56

- name: Enabling ufw with - ufw enable
  command: /usr/sbin/ufw enable

- name: Get ufw status numbered
  ansible.builtin.command: /usr/sbin/ufw status numbered
  register: get_ufw_status

- name: Print ufw status numbered
  ansible.builtin.debug:
    var: get_ufw_status.stdout_lines

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

